baseURL = "https://blog.derreineke.com/"
languageCode = "en-us"
title = "derreineke@meatspace"
theme = "hugo-base16-theme"
copyright = "Reineke Fuchs"
publishDir = "docs"

pygmentsuseclasses = true

[menu]
    [[menu.main]]
        name = "posts"
        indentifier = "posts"
        url = "/posts"
